### ISSUE TITLE
Job Descriptions (page) + (section)

### ISSUE THREAD

**Issue by bryanwillis** [MBIStaffing/website#12]
We need 1-2 sentence description of each job. Not sure if we have this already. 

Accounts Payable Clerk
Sr. Developer
BigFix
Accounts Payable Clerk
BigFix
Business Analyst
Change Manager
CRM Product Specialist
Data Analyst
Design Documentation Engineer
Deskside Support Technician
Devops
Exchange and Office 365 Administrator
Executive Administrator
Firewall Engineer
Global Active Directory
GNOC Team Lead
Help Desk Advisor
Help Desk Project Manager
IT Project Manager - Separation
Incident Manager
Infrastructure Project Manager
Integration Project Manager
IT Analyst
IT Architect - Cloud
IT Architect - Enterprise VMware Storage
IT Architect - VMware Server
IT Architect - VoIP and Video
IT Operations Engineer
IT Product Specialist
IT Project Manager
IT Security Analyst
IT Security Delivery Manager
JDE 1
McAfee EPO Admin
Mobile Apps Developer
.NET Developer 
Network & VPN Expert
Operations Manager
OSX Implementation Engineer
Product Owner
Project Specialist
SAN Architect
SAN Engineer
Scripting Resource
Server Team Lead / Server Admin
Sr. Developer
SSO Federation
Svc Delivery Manager
Technical Business Analyst
Technical Writer
TM1 Admin or Developer
VMware Admin / Engineer / Architect
Wireless Expert
Wireless Pooling Support

**Comment by classicone2day** [comment]
I would get the general info from Joe or Chris on these and I can help you word smith them to give them more of a polished look and feel.
