### ISSUE TITLE
Live Chat

### ISSUE THREAD

**Issue by bryanwillis** [MBIStaffing/website#14]
What do you guys think of this? Mainly it'd be for Mayra, but we can initiate it on different pages saying different things so it seems like someone is always there to help. It will only show active if Mayra has the chat open so I can't really see any downside to this.

http://mbistaffing.com/contact/

**Comment by joedmbi** [comment]
I love it.  Definitely add to website in my opinion

**Comment by mayra1755** [comment]
That looks great!

**Comment by bryanwillis** [comment]
@mayra1755 - **Mayra here's the desktop chat app you can download:**

https://www.livechatinc.com/applications/livechat-for-windows/

**Comment by mayra1755** [comment]
Do I already have a user name and password?

**Comment by bryanwillis** [comment]
It looks like youre loogged in.. DId you figure it out? I'm going to swing by the office.

**Comment by mayra1755** [comment]
Yeah I figured it out.
